// ignore_for_file: constant_identifier_names
// ? Add New Values to Enum whenever a new unit is added

enum UnitEnum {
  length_meter,
  length_kilometer,
  length_centimeter,
  length_millimeter,
  length_inch,
  length_foot,
  length_yard,
  length_mile,
  weight_killogram,
  weight_gram,
  weight_miligram,
  weight_pound,
  weight_ounce,
  temperature_celsius,
  temperature_fahrenheit,
  temperature_kelvin,
  volume_fluidOunce,
  volume_gallon,
  volume_quart,
  volume_pint,
  volume_cubicMeter,
  volume_cubicCentimeter,
  volume_milliliter,
  volume_liter,
  area_squareMeter,
  area_squareKilometer,
  area_squareCentimeter,
  area_squareInch,
  area_squareFoot,
  area_acre,
  area_hectare,
  speed_meterPerSecond,
  speed_kilometerPerHour,
  speed_milePerHour,
  time_second,
  time_minute,
  time_hour,
  time_day,
  energy_joule,
  energy_kilocalorie,
  energy_calorie
}
